### ISSUE TITLE
[Bug report] Crash when parsing command-line arguments

### ISSUE THREAD

**Issue by AdamKorcz** [googleapis/gnostic#174]
[The newly added fuzzer](https://github.com/googleapis/gnostic/pull/171) finds a crash in gnostic.go.

Here are 5 test cases from the fuzzer:
**1:**
```
^@^N


-
```

**2:**
```
t



-
```
**3:**
`:&<86>^@^@      -       ÿ       ÿ       ^@`

**4:**
`^P^K-^M¿`

**5:**
`:       -`

They all follow the same stack trace:
```
panic: runtime error: index out of range [1] with length 1

goroutine 17 [running, locked to thread]:
github.com/googleapis/gnostic/lib.(*Gnostic).readOptions(0x10c000247a40, 0x5, 0x0)
        github.com/googleapis/gnostic/lib/gnostic.go:348 +0x10f1
github.com/googleapis/gnostic/lib.(*Gnostic).Main(0x10c000247a40, 0x0, 0x0)
        github.com/googleapis/gnostic/lib/gnostic.go:598 +0x1b7
github.com/googleapis/gnostic/fuzz.Fuzz(0x602000025070, 0xe, 0xe, 0x18)
        github.com/googleapis/gnostic/fuzz/fuzz.go:29 +0x16a

```

**Comment by timburks** [comment]
Thanks for this!

**Comment by AdamKorcz** [comment]
My pleasure!
